//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteCalculadora.cliente {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servidorcalculadora/", ConfigurationName="cliente.Calculadora")]
    public interface Calculadora {
        
        // CODEGEN: Gerando contrato de mensagem porque o namespace de parte da mensagem () não corresponde ao valor padrão (http://servidorcalculadora/)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteCalculadora.cliente.powResponse pow(ClienteCalculadora.cliente.powRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteCalculadora.cliente.powResponse> powAsync(ClienteCalculadora.cliente.powRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o namespace de parte da mensagem () não corresponde ao valor padrão (http://servidorcalculadora/)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteCalculadora.cliente.modResponse mod(ClienteCalculadora.cliente.modRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteCalculadora.cliente.modResponse> modAsync(ClienteCalculadora.cliente.modRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o namespace de parte da mensagem () não corresponde ao valor padrão (http://servidorcalculadora/)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteCalculadora.cliente.subResponse sub(ClienteCalculadora.cliente.subRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteCalculadora.cliente.subResponse> subAsync(ClienteCalculadora.cliente.subRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o namespace de parte da mensagem () não corresponde ao valor padrão (http://servidorcalculadora/)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteCalculadora.cliente.sumResponse sum(ClienteCalculadora.cliente.sumRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteCalculadora.cliente.sumResponse> sumAsync(ClienteCalculadora.cliente.sumRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o namespace de parte da mensagem () não corresponde ao valor padrão (http://servidorcalculadora/)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteCalculadora.cliente.multResponse mult(ClienteCalculadora.cliente.multRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteCalculadora.cliente.multResponse> multAsync(ClienteCalculadora.cliente.multRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o namespace de parte da mensagem () não corresponde ao valor padrão (http://servidorcalculadora/)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteCalculadora.cliente.divResponse div(ClienteCalculadora.cliente.divRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteCalculadora.cliente.divResponse> divAsync(ClienteCalculadora.cliente.divRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o namespace de parte da mensagem () não corresponde ao valor padrão (http://servidorcalculadora/)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteCalculadora.cliente.sqtResponse sqt(ClienteCalculadora.cliente.sqtRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteCalculadora.cliente.sqtResponse> sqtAsync(ClienteCalculadora.cliente.sqtRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pow", WrapperNamespace="http://servidorcalculadora/", IsWrapped=true)]
    public partial class powRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double arg1;
        
        public powRequest() {
        }
        
        public powRequest(double arg0, double arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="powResponse", WrapperNamespace="http://servidorcalculadora/", IsWrapped=true)]
    public partial class powResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public powResponse() {
        }
        
        public powResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mod", WrapperNamespace="http://servidorcalculadora/", IsWrapped=true)]
    public partial class modRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double arg1;
        
        public modRequest() {
        }
        
        public modRequest(double arg0, double arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modResponse", WrapperNamespace="http://servidorcalculadora/", IsWrapped=true)]
    public partial class modResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public modResponse() {
        }
        
        public modResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sub", WrapperNamespace="http://servidorcalculadora/", IsWrapped=true)]
    public partial class subRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double arg1;
        
        public subRequest() {
        }
        
        public subRequest(double arg0, double arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="subResponse", WrapperNamespace="http://servidorcalculadora/", IsWrapped=true)]
    public partial class subResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public subResponse() {
        }
        
        public subResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sum", WrapperNamespace="http://servidorcalculadora/", IsWrapped=true)]
    public partial class sumRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double arg1;
        
        public sumRequest() {
        }
        
        public sumRequest(double arg0, double arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sumResponse", WrapperNamespace="http://servidorcalculadora/", IsWrapped=true)]
    public partial class sumResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public sumResponse() {
        }
        
        public sumResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mult", WrapperNamespace="http://servidorcalculadora/", IsWrapped=true)]
    public partial class multRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double arg1;
        
        public multRequest() {
        }
        
        public multRequest(double arg0, double arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="multResponse", WrapperNamespace="http://servidorcalculadora/", IsWrapped=true)]
    public partial class multResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public multResponse() {
        }
        
        public multResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="div", WrapperNamespace="http://servidorcalculadora/", IsWrapped=true)]
    public partial class divRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double arg1;
        
        public divRequest() {
        }
        
        public divRequest(double arg0, double arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="divResponse", WrapperNamespace="http://servidorcalculadora/", IsWrapped=true)]
    public partial class divResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public divResponse() {
        }
        
        public divResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sqt", WrapperNamespace="http://servidorcalculadora/", IsWrapped=true)]
    public partial class sqtRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        public sqtRequest() {
        }
        
        public sqtRequest(double arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sqtResponse", WrapperNamespace="http://servidorcalculadora/", IsWrapped=true)]
    public partial class sqtResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public sqtResponse() {
        }
        
        public sqtResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculadoraChannel : ClienteCalculadora.cliente.Calculadora, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculadoraClient : System.ServiceModel.ClientBase<ClienteCalculadora.cliente.Calculadora>, ClienteCalculadora.cliente.Calculadora {
        
        public CalculadoraClient() {
        }
        
        public CalculadoraClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculadoraClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculadoraClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculadoraClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteCalculadora.cliente.powResponse ClienteCalculadora.cliente.Calculadora.pow(ClienteCalculadora.cliente.powRequest request) {
            return base.Channel.pow(request);
        }
        
        public double pow(double arg0, double arg1) {
            ClienteCalculadora.cliente.powRequest inValue = new ClienteCalculadora.cliente.powRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            ClienteCalculadora.cliente.powResponse retVal = ((ClienteCalculadora.cliente.Calculadora)(this)).pow(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteCalculadora.cliente.powResponse> ClienteCalculadora.cliente.Calculadora.powAsync(ClienteCalculadora.cliente.powRequest request) {
            return base.Channel.powAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteCalculadora.cliente.powResponse> powAsync(double arg0, double arg1) {
            ClienteCalculadora.cliente.powRequest inValue = new ClienteCalculadora.cliente.powRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((ClienteCalculadora.cliente.Calculadora)(this)).powAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteCalculadora.cliente.modResponse ClienteCalculadora.cliente.Calculadora.mod(ClienteCalculadora.cliente.modRequest request) {
            return base.Channel.mod(request);
        }
        
        public double mod(double arg0, double arg1) {
            ClienteCalculadora.cliente.modRequest inValue = new ClienteCalculadora.cliente.modRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            ClienteCalculadora.cliente.modResponse retVal = ((ClienteCalculadora.cliente.Calculadora)(this)).mod(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteCalculadora.cliente.modResponse> ClienteCalculadora.cliente.Calculadora.modAsync(ClienteCalculadora.cliente.modRequest request) {
            return base.Channel.modAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteCalculadora.cliente.modResponse> modAsync(double arg0, double arg1) {
            ClienteCalculadora.cliente.modRequest inValue = new ClienteCalculadora.cliente.modRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((ClienteCalculadora.cliente.Calculadora)(this)).modAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteCalculadora.cliente.subResponse ClienteCalculadora.cliente.Calculadora.sub(ClienteCalculadora.cliente.subRequest request) {
            return base.Channel.sub(request);
        }
        
        public double sub(double arg0, double arg1) {
            ClienteCalculadora.cliente.subRequest inValue = new ClienteCalculadora.cliente.subRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            ClienteCalculadora.cliente.subResponse retVal = ((ClienteCalculadora.cliente.Calculadora)(this)).sub(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteCalculadora.cliente.subResponse> ClienteCalculadora.cliente.Calculadora.subAsync(ClienteCalculadora.cliente.subRequest request) {
            return base.Channel.subAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteCalculadora.cliente.subResponse> subAsync(double arg0, double arg1) {
            ClienteCalculadora.cliente.subRequest inValue = new ClienteCalculadora.cliente.subRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((ClienteCalculadora.cliente.Calculadora)(this)).subAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteCalculadora.cliente.sumResponse ClienteCalculadora.cliente.Calculadora.sum(ClienteCalculadora.cliente.sumRequest request) {
            return base.Channel.sum(request);
        }
        
        public double sum(double arg0, double arg1) {
            ClienteCalculadora.cliente.sumRequest inValue = new ClienteCalculadora.cliente.sumRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            ClienteCalculadora.cliente.sumResponse retVal = ((ClienteCalculadora.cliente.Calculadora)(this)).sum(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteCalculadora.cliente.sumResponse> ClienteCalculadora.cliente.Calculadora.sumAsync(ClienteCalculadora.cliente.sumRequest request) {
            return base.Channel.sumAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteCalculadora.cliente.sumResponse> sumAsync(double arg0, double arg1) {
            ClienteCalculadora.cliente.sumRequest inValue = new ClienteCalculadora.cliente.sumRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((ClienteCalculadora.cliente.Calculadora)(this)).sumAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteCalculadora.cliente.multResponse ClienteCalculadora.cliente.Calculadora.mult(ClienteCalculadora.cliente.multRequest request) {
            return base.Channel.mult(request);
        }
        
        public double mult(double arg0, double arg1) {
            ClienteCalculadora.cliente.multRequest inValue = new ClienteCalculadora.cliente.multRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            ClienteCalculadora.cliente.multResponse retVal = ((ClienteCalculadora.cliente.Calculadora)(this)).mult(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteCalculadora.cliente.multResponse> ClienteCalculadora.cliente.Calculadora.multAsync(ClienteCalculadora.cliente.multRequest request) {
            return base.Channel.multAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteCalculadora.cliente.multResponse> multAsync(double arg0, double arg1) {
            ClienteCalculadora.cliente.multRequest inValue = new ClienteCalculadora.cliente.multRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((ClienteCalculadora.cliente.Calculadora)(this)).multAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteCalculadora.cliente.divResponse ClienteCalculadora.cliente.Calculadora.div(ClienteCalculadora.cliente.divRequest request) {
            return base.Channel.div(request);
        }
        
        public double div(double arg0, double arg1) {
            ClienteCalculadora.cliente.divRequest inValue = new ClienteCalculadora.cliente.divRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            ClienteCalculadora.cliente.divResponse retVal = ((ClienteCalculadora.cliente.Calculadora)(this)).div(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteCalculadora.cliente.divResponse> ClienteCalculadora.cliente.Calculadora.divAsync(ClienteCalculadora.cliente.divRequest request) {
            return base.Channel.divAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteCalculadora.cliente.divResponse> divAsync(double arg0, double arg1) {
            ClienteCalculadora.cliente.divRequest inValue = new ClienteCalculadora.cliente.divRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((ClienteCalculadora.cliente.Calculadora)(this)).divAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteCalculadora.cliente.sqtResponse ClienteCalculadora.cliente.Calculadora.sqt(ClienteCalculadora.cliente.sqtRequest request) {
            return base.Channel.sqt(request);
        }
        
        public double sqt(double arg0) {
            ClienteCalculadora.cliente.sqtRequest inValue = new ClienteCalculadora.cliente.sqtRequest();
            inValue.arg0 = arg0;
            ClienteCalculadora.cliente.sqtResponse retVal = ((ClienteCalculadora.cliente.Calculadora)(this)).sqt(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteCalculadora.cliente.sqtResponse> ClienteCalculadora.cliente.Calculadora.sqtAsync(ClienteCalculadora.cliente.sqtRequest request) {
            return base.Channel.sqtAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteCalculadora.cliente.sqtResponse> sqtAsync(double arg0) {
            ClienteCalculadora.cliente.sqtRequest inValue = new ClienteCalculadora.cliente.sqtRequest();
            inValue.arg0 = arg0;
            return ((ClienteCalculadora.cliente.Calculadora)(this)).sqtAsync(inValue);
        }
    }
}
