//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteCalculadora.ServiceReferenceCliente {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servidorcalculadora/", ConfigurationName="ServiceReferenceCliente.Calculadora")]
    public interface Calculadora {
        
        // CODEGEN: Gerando contrato de mensagem porque o namespace de parte da mensagem () não corresponde ao valor padrão (http://servidorcalculadora/)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteCalculadora.ServiceReferenceCliente.logResponse log(ClienteCalculadora.ServiceReferenceCliente.logRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteCalculadora.ServiceReferenceCliente.logResponse> logAsync(ClienteCalculadora.ServiceReferenceCliente.logRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o namespace de parte da mensagem () não corresponde ao valor padrão (http://servidorcalculadora/)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteCalculadora.ServiceReferenceCliente.powResponse pow(ClienteCalculadora.ServiceReferenceCliente.powRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteCalculadora.ServiceReferenceCliente.powResponse> powAsync(ClienteCalculadora.ServiceReferenceCliente.powRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o namespace de parte da mensagem () não corresponde ao valor padrão (http://servidorcalculadora/)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteCalculadora.ServiceReferenceCliente.modResponse mod(ClienteCalculadora.ServiceReferenceCliente.modRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteCalculadora.ServiceReferenceCliente.modResponse> modAsync(ClienteCalculadora.ServiceReferenceCliente.modRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o namespace de parte da mensagem () não corresponde ao valor padrão (http://servidorcalculadora/)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteCalculadora.ServiceReferenceCliente.subResponse sub(ClienteCalculadora.ServiceReferenceCliente.subRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteCalculadora.ServiceReferenceCliente.subResponse> subAsync(ClienteCalculadora.ServiceReferenceCliente.subRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o namespace de parte da mensagem () não corresponde ao valor padrão (http://servidorcalculadora/)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteCalculadora.ServiceReferenceCliente.sumResponse sum(ClienteCalculadora.ServiceReferenceCliente.sumRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteCalculadora.ServiceReferenceCliente.sumResponse> sumAsync(ClienteCalculadora.ServiceReferenceCliente.sumRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o namespace de parte da mensagem () não corresponde ao valor padrão (http://servidorcalculadora/)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteCalculadora.ServiceReferenceCliente.multResponse mult(ClienteCalculadora.ServiceReferenceCliente.multRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteCalculadora.ServiceReferenceCliente.multResponse> multAsync(ClienteCalculadora.ServiceReferenceCliente.multRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o namespace de parte da mensagem () não corresponde ao valor padrão (http://servidorcalculadora/)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteCalculadora.ServiceReferenceCliente.divResponse div(ClienteCalculadora.ServiceReferenceCliente.divRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteCalculadora.ServiceReferenceCliente.divResponse> divAsync(ClienteCalculadora.ServiceReferenceCliente.divRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o namespace de parte da mensagem () não corresponde ao valor padrão (http://servidorcalculadora/)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteCalculadora.ServiceReferenceCliente.sqtResponse sqt(ClienteCalculadora.ServiceReferenceCliente.sqtRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteCalculadora.ServiceReferenceCliente.sqtResponse> sqtAsync(ClienteCalculadora.ServiceReferenceCliente.sqtRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="log", WrapperNamespace="http://servidorcalculadora/", IsWrapped=true)]
    public partial class logRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        public logRequest() {
        }
        
        public logRequest(double arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="logResponse", WrapperNamespace="http://servidorcalculadora/", IsWrapped=true)]
    public partial class logResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public logResponse() {
        }
        
        public logResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pow", WrapperNamespace="http://servidorcalculadora/", IsWrapped=true)]
    public partial class powRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double arg1;
        
        public powRequest() {
        }
        
        public powRequest(double arg0, double arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="powResponse", WrapperNamespace="http://servidorcalculadora/", IsWrapped=true)]
    public partial class powResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public powResponse() {
        }
        
        public powResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mod", WrapperNamespace="http://servidorcalculadora/", IsWrapped=true)]
    public partial class modRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double arg1;
        
        public modRequest() {
        }
        
        public modRequest(double arg0, double arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modResponse", WrapperNamespace="http://servidorcalculadora/", IsWrapped=true)]
    public partial class modResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public modResponse() {
        }
        
        public modResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sub", WrapperNamespace="http://servidorcalculadora/", IsWrapped=true)]
    public partial class subRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double arg1;
        
        public subRequest() {
        }
        
        public subRequest(double arg0, double arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="subResponse", WrapperNamespace="http://servidorcalculadora/", IsWrapped=true)]
    public partial class subResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public subResponse() {
        }
        
        public subResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sum", WrapperNamespace="http://servidorcalculadora/", IsWrapped=true)]
    public partial class sumRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double arg1;
        
        public sumRequest() {
        }
        
        public sumRequest(double arg0, double arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sumResponse", WrapperNamespace="http://servidorcalculadora/", IsWrapped=true)]
    public partial class sumResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public sumResponse() {
        }
        
        public sumResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mult", WrapperNamespace="http://servidorcalculadora/", IsWrapped=true)]
    public partial class multRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double arg1;
        
        public multRequest() {
        }
        
        public multRequest(double arg0, double arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="multResponse", WrapperNamespace="http://servidorcalculadora/", IsWrapped=true)]
    public partial class multResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public multResponse() {
        }
        
        public multResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="div", WrapperNamespace="http://servidorcalculadora/", IsWrapped=true)]
    public partial class divRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double arg1;
        
        public divRequest() {
        }
        
        public divRequest(double arg0, double arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="divResponse", WrapperNamespace="http://servidorcalculadora/", IsWrapped=true)]
    public partial class divResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public divResponse() {
        }
        
        public divResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sqt", WrapperNamespace="http://servidorcalculadora/", IsWrapped=true)]
    public partial class sqtRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        public sqtRequest() {
        }
        
        public sqtRequest(double arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sqtResponse", WrapperNamespace="http://servidorcalculadora/", IsWrapped=true)]
    public partial class sqtResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public sqtResponse() {
        }
        
        public sqtResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculadoraChannel : ClienteCalculadora.ServiceReferenceCliente.Calculadora, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculadoraClient : System.ServiceModel.ClientBase<ClienteCalculadora.ServiceReferenceCliente.Calculadora>, ClienteCalculadora.ServiceReferenceCliente.Calculadora {
        
        public CalculadoraClient() {
        }
        
        public CalculadoraClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculadoraClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculadoraClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculadoraClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteCalculadora.ServiceReferenceCliente.logResponse ClienteCalculadora.ServiceReferenceCliente.Calculadora.log(ClienteCalculadora.ServiceReferenceCliente.logRequest request) {
            return base.Channel.log(request);
        }
        
        public double log(double arg0) {
            ClienteCalculadora.ServiceReferenceCliente.logRequest inValue = new ClienteCalculadora.ServiceReferenceCliente.logRequest();
            inValue.arg0 = arg0;
            ClienteCalculadora.ServiceReferenceCliente.logResponse retVal = ((ClienteCalculadora.ServiceReferenceCliente.Calculadora)(this)).log(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteCalculadora.ServiceReferenceCliente.logResponse> ClienteCalculadora.ServiceReferenceCliente.Calculadora.logAsync(ClienteCalculadora.ServiceReferenceCliente.logRequest request) {
            return base.Channel.logAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteCalculadora.ServiceReferenceCliente.logResponse> logAsync(double arg0) {
            ClienteCalculadora.ServiceReferenceCliente.logRequest inValue = new ClienteCalculadora.ServiceReferenceCliente.logRequest();
            inValue.arg0 = arg0;
            return ((ClienteCalculadora.ServiceReferenceCliente.Calculadora)(this)).logAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteCalculadora.ServiceReferenceCliente.powResponse ClienteCalculadora.ServiceReferenceCliente.Calculadora.pow(ClienteCalculadora.ServiceReferenceCliente.powRequest request) {
            return base.Channel.pow(request);
        }
        
        public double pow(double arg0, double arg1) {
            ClienteCalculadora.ServiceReferenceCliente.powRequest inValue = new ClienteCalculadora.ServiceReferenceCliente.powRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            ClienteCalculadora.ServiceReferenceCliente.powResponse retVal = ((ClienteCalculadora.ServiceReferenceCliente.Calculadora)(this)).pow(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteCalculadora.ServiceReferenceCliente.powResponse> ClienteCalculadora.ServiceReferenceCliente.Calculadora.powAsync(ClienteCalculadora.ServiceReferenceCliente.powRequest request) {
            return base.Channel.powAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteCalculadora.ServiceReferenceCliente.powResponse> powAsync(double arg0, double arg1) {
            ClienteCalculadora.ServiceReferenceCliente.powRequest inValue = new ClienteCalculadora.ServiceReferenceCliente.powRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((ClienteCalculadora.ServiceReferenceCliente.Calculadora)(this)).powAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteCalculadora.ServiceReferenceCliente.modResponse ClienteCalculadora.ServiceReferenceCliente.Calculadora.mod(ClienteCalculadora.ServiceReferenceCliente.modRequest request) {
            return base.Channel.mod(request);
        }
        
        public double mod(double arg0, double arg1) {
            ClienteCalculadora.ServiceReferenceCliente.modRequest inValue = new ClienteCalculadora.ServiceReferenceCliente.modRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            ClienteCalculadora.ServiceReferenceCliente.modResponse retVal = ((ClienteCalculadora.ServiceReferenceCliente.Calculadora)(this)).mod(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteCalculadora.ServiceReferenceCliente.modResponse> ClienteCalculadora.ServiceReferenceCliente.Calculadora.modAsync(ClienteCalculadora.ServiceReferenceCliente.modRequest request) {
            return base.Channel.modAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteCalculadora.ServiceReferenceCliente.modResponse> modAsync(double arg0, double arg1) {
            ClienteCalculadora.ServiceReferenceCliente.modRequest inValue = new ClienteCalculadora.ServiceReferenceCliente.modRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((ClienteCalculadora.ServiceReferenceCliente.Calculadora)(this)).modAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteCalculadora.ServiceReferenceCliente.subResponse ClienteCalculadora.ServiceReferenceCliente.Calculadora.sub(ClienteCalculadora.ServiceReferenceCliente.subRequest request) {
            return base.Channel.sub(request);
        }
        
        public double sub(double arg0, double arg1) {
            ClienteCalculadora.ServiceReferenceCliente.subRequest inValue = new ClienteCalculadora.ServiceReferenceCliente.subRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            ClienteCalculadora.ServiceReferenceCliente.subResponse retVal = ((ClienteCalculadora.ServiceReferenceCliente.Calculadora)(this)).sub(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteCalculadora.ServiceReferenceCliente.subResponse> ClienteCalculadora.ServiceReferenceCliente.Calculadora.subAsync(ClienteCalculadora.ServiceReferenceCliente.subRequest request) {
            return base.Channel.subAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteCalculadora.ServiceReferenceCliente.subResponse> subAsync(double arg0, double arg1) {
            ClienteCalculadora.ServiceReferenceCliente.subRequest inValue = new ClienteCalculadora.ServiceReferenceCliente.subRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((ClienteCalculadora.ServiceReferenceCliente.Calculadora)(this)).subAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteCalculadora.ServiceReferenceCliente.sumResponse ClienteCalculadora.ServiceReferenceCliente.Calculadora.sum(ClienteCalculadora.ServiceReferenceCliente.sumRequest request) {
            return base.Channel.sum(request);
        }
        
        public double sum(double arg0, double arg1) {
            ClienteCalculadora.ServiceReferenceCliente.sumRequest inValue = new ClienteCalculadora.ServiceReferenceCliente.sumRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            ClienteCalculadora.ServiceReferenceCliente.sumResponse retVal = ((ClienteCalculadora.ServiceReferenceCliente.Calculadora)(this)).sum(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteCalculadora.ServiceReferenceCliente.sumResponse> ClienteCalculadora.ServiceReferenceCliente.Calculadora.sumAsync(ClienteCalculadora.ServiceReferenceCliente.sumRequest request) {
            return base.Channel.sumAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteCalculadora.ServiceReferenceCliente.sumResponse> sumAsync(double arg0, double arg1) {
            ClienteCalculadora.ServiceReferenceCliente.sumRequest inValue = new ClienteCalculadora.ServiceReferenceCliente.sumRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((ClienteCalculadora.ServiceReferenceCliente.Calculadora)(this)).sumAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteCalculadora.ServiceReferenceCliente.multResponse ClienteCalculadora.ServiceReferenceCliente.Calculadora.mult(ClienteCalculadora.ServiceReferenceCliente.multRequest request) {
            return base.Channel.mult(request);
        }
        
        public double mult(double arg0, double arg1) {
            ClienteCalculadora.ServiceReferenceCliente.multRequest inValue = new ClienteCalculadora.ServiceReferenceCliente.multRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            ClienteCalculadora.ServiceReferenceCliente.multResponse retVal = ((ClienteCalculadora.ServiceReferenceCliente.Calculadora)(this)).mult(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteCalculadora.ServiceReferenceCliente.multResponse> ClienteCalculadora.ServiceReferenceCliente.Calculadora.multAsync(ClienteCalculadora.ServiceReferenceCliente.multRequest request) {
            return base.Channel.multAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteCalculadora.ServiceReferenceCliente.multResponse> multAsync(double arg0, double arg1) {
            ClienteCalculadora.ServiceReferenceCliente.multRequest inValue = new ClienteCalculadora.ServiceReferenceCliente.multRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((ClienteCalculadora.ServiceReferenceCliente.Calculadora)(this)).multAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteCalculadora.ServiceReferenceCliente.divResponse ClienteCalculadora.ServiceReferenceCliente.Calculadora.div(ClienteCalculadora.ServiceReferenceCliente.divRequest request) {
            return base.Channel.div(request);
        }
        
        public double div(double arg0, double arg1) {
            ClienteCalculadora.ServiceReferenceCliente.divRequest inValue = new ClienteCalculadora.ServiceReferenceCliente.divRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            ClienteCalculadora.ServiceReferenceCliente.divResponse retVal = ((ClienteCalculadora.ServiceReferenceCliente.Calculadora)(this)).div(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteCalculadora.ServiceReferenceCliente.divResponse> ClienteCalculadora.ServiceReferenceCliente.Calculadora.divAsync(ClienteCalculadora.ServiceReferenceCliente.divRequest request) {
            return base.Channel.divAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteCalculadora.ServiceReferenceCliente.divResponse> divAsync(double arg0, double arg1) {
            ClienteCalculadora.ServiceReferenceCliente.divRequest inValue = new ClienteCalculadora.ServiceReferenceCliente.divRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((ClienteCalculadora.ServiceReferenceCliente.Calculadora)(this)).divAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteCalculadora.ServiceReferenceCliente.sqtResponse ClienteCalculadora.ServiceReferenceCliente.Calculadora.sqt(ClienteCalculadora.ServiceReferenceCliente.sqtRequest request) {
            return base.Channel.sqt(request);
        }
        
        public double sqt(double arg0) {
            ClienteCalculadora.ServiceReferenceCliente.sqtRequest inValue = new ClienteCalculadora.ServiceReferenceCliente.sqtRequest();
            inValue.arg0 = arg0;
            ClienteCalculadora.ServiceReferenceCliente.sqtResponse retVal = ((ClienteCalculadora.ServiceReferenceCliente.Calculadora)(this)).sqt(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteCalculadora.ServiceReferenceCliente.sqtResponse> ClienteCalculadora.ServiceReferenceCliente.Calculadora.sqtAsync(ClienteCalculadora.ServiceReferenceCliente.sqtRequest request) {
            return base.Channel.sqtAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteCalculadora.ServiceReferenceCliente.sqtResponse> sqtAsync(double arg0) {
            ClienteCalculadora.ServiceReferenceCliente.sqtRequest inValue = new ClienteCalculadora.ServiceReferenceCliente.sqtRequest();
            inValue.arg0 = arg0;
            return ((ClienteCalculadora.ServiceReferenceCliente.Calculadora)(this)).sqtAsync(inValue);
        }
    }
}
